### ISSUE TITLE
Add feature of ignoring certain url patterns

### ISSUE THREAD

**Issue by IsabellaDev** [yzwdroid/goURL#7]
Hi, would you mind that I add a feature that allows passing an argument like -i or --ignore to ignore specific link patterns? Thanks.

**Comment by yzwdroid** [comment]
Ok, go ahead. I'll assign you this issue

**Comment by IsabellaDev** [comment]
Please check my branch [https://github.com/isabellaliu77/goURL/tree/issue-7](https://github.com/isabellaliu77/goURL/tree/issue-7). Any problem, let me know.

**Comment by yzwdroid** [comment]
Everything looks good, I have already merged your work. Thanks.
